<?php

/**
 * pt-br: Impede que o arquivo seja executado fora do WordPress
 * 
 * en: Prevents the file from running outside of WordPress.
 */
if (!defined('ABSPATH')) {
    exit;
}

/**
 * pt-br: Classe responsável por registrar os estilos do tema.
 * 
 * en: Class responsible for registering theme styles.
 */
class Pragmatico_Styles
{
    public function __construct()
    {
        add_action('wp_enqueue_scripts', [$this, 'enqueue_styles']);
    }

    public function enqueue_styles()
    {
        /**
         * pt-br: Enfileira o arquivo CSS gerado pelo Tailwind.
         * 
         * en: Enqueues the CSS file generated by Tailwind.
         */
        $style_path = get_template_directory() . '/src/output.css';
        $style_uri = get_template_directory_uri() . '/src/output.css';
        $version = file_exists($style_path) ? filemtime($style_path) : wp_get_theme()->get('Version');

        wp_enqueue_style('pragmatico-output', $style_uri, [], $version);
    }
}

new Pragmatico_Styles();
